### ISSUE TITLE
Installation of Unix Executable 

### ISSUE THREAD

**Issue by zivkaziv** [KosalaHerath/macos-installer-builder#1]
Hi,

I'm looking for a way to install Unix Executable file and add it to the PATH.
Is there an option to do so?

Thanks
Ziv

**Comment by KosalaHerath** [comment]
You can add the executable file into the application folder and using the **_macos-installer-builder/macOS-x64/darwin/scripts/postinstall_** script you change permissions of the file and add to the PATH. You can do all the post-install process using this _postinstall_ script which runs after the installation (copying files). Hope you got the answer.

**Comment by KosalaHerath** [comment]
Since the matter has been answered closing the issue. Please create aa new issue if you need more help on this.
