### ISSUE TITLE
[Question] how to change application /Library/${product_name}/${version} to other directory?

### ISSUE THREAD

**Issue by MichelleJin12** [KosalaHerath/macos-installer-builder#11]
Hello, Thank you for inventing this cool open source.

However, I have a difficulty to changing application directory when .pkg installed.

I actually don't know much about shell programming, so can you let me know how to do this?

Thank you so much.

**Comment by KosalaHerath** [comment]
It's great to hear that this has helped you.

You can copy your application files into any directory path from the root (/).

You need to create the directory path in "**darwinpkg**" directory and copy your application files onto that before creating the installer as given in [here](https://github.com/KosalaHerath/macos-installer-builder/blob/master/macOS-x64/build-macos-x64.sh#L119).

As an example, I can create a directory path in "**darwinpkg**" as following:

`/Library/${PRODUCT}/${VERSION}`

Therefore, the installer will copy files as the same path starting from the root (/).

On the other hand, if you want to copy files to

`"/Users/name/Documents/${PRODUCT}/${VERSION}"`

you have to change these [lines](https://github.com/KosalaHerath/macos-installer-builder/blob/master/macOS-x64/build-macos-x64.sh#L119) according to that replacing

`"/Library/${PRODUCT}/${VERSION}"`

 with

`"/Users/name/Documents/${PRODUCT}/${VERSION}"`

[This article](https://medium.com/swlh/the-easiest-way-to-build-macos-installer-for-your-application-34a11dd08744) will help you with more details. 

Cheers!

**Comment by KosalaHerath** [comment]
Closing since the answer is provided.
