### ISSUE TITLE
Picture cannot be shown in conclusion.html

### ISSUE THREAD

**Issue by ghost** [KosalaHerath/macos-installer-builder#14]
Hi,

This is a powerful tool. But now I want to add one QR Code in the complete page, I tried load picture from internet, from local and encode picture as base64 in the conclusion.html. But the picture cannot be shown. Please let me know whether you have any suggestion for this. Thank you!

**Comment by KosalaHerath** [comment]
Thank you very much. IMO, the welcome page and conclusion page only supports text format and does not support other data types as you see in the log.

<img width="843" alt="Screen Shot 2021-05-07 at 11 09 14 am" src="https://user-images.githubusercontent.com/33099111/117383686-ab25d980-af24-11eb-9e90-c3cd3d713ccc.png">

In addition, in the Apple reference, this has been mentioned.
https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Distribution_XML_Ref.html#//apple_ref/doc/uid/TP40005370-CH100-SW6

Hope this will be helpful. Cheers!

**Comment by KosalaHerath** [comment]
Since no reply, closing the issue.
