### ISSUE TITLE
Destination Select shows only one Option "Install for All Users"

### ISSUE THREAD

**Issue by ChethanEJ7** [KosalaHerath/macos-installer-builder#15]
As an application packager, how can i give multiple option to the user.
Example : I want to add an option "Install Only for Me" , "Install for All users".

May i know which lines of codes to be modified in build.sh file to make this work as expected.

**Comment by KosalaHerath** [comment]
Hope this will be helpful:
https://stackoverflow.com/questions/12863944/how-do-you-specify-a-default-install-location-to-home-with-pkgbuild

**Comment by ChethanEJ7** [comment]
Hey,

Yep it worked :) Thanks aton

Thanks and Regards
Chethan EJ
9740857984
________________________________
