### ISSUE TITLE
Banner image does not display on dark theme (fix included)

### ISSUE THREAD

**Issue by meverett** [KosalaHerath/macos-installer-builder#16]
Banner images will not display as part of installer packages for macOS using dark theme. The [Distribution file](https://github.com/KosalaHerath/macos-installer-builder/blob/master/macOS-x64/darwin/Distribution) needs to have an additional line added:

This:
```xml
<background mime-type="image/png" file="banner.png" scaling="proportional"/>
```

Should become this:
```xml
<background mime-type="image/png" file="banner.png" scaling="proportional"/>
<background-darkAqua mime-type="image/png" file="banner.png" scaling="proportional"/>
```

Cheers

**Comment by KosalaHerath** [comment]
Fixed. Thank you for your contribution.
