### ISSUE TITLE
Medium article is behind a pay/login wall

### ISSUE THREAD

**Issue by bumi** [KosalaHerath/macos-installer-builder#20]
Currently it is not possible to read the medium article that is referred to from the Readme. 
Maybe copy relevant parts to the readme to make it accessible for people without medium login.

**Comment by KosalaHerath** [comment]
Sorry about the inconvenience. I will update the readme.

**Comment by KosalaHerath** [comment]
Update the README with essential instructions (https://github.com/KosalaHerath/macos-installer-builder/commit/89fa0ec9fcd5c502439089cb4c6e9e6af38be27d)
