### ISSUE TITLE
Commands in post install

### ISSUE THREAD

**Issue by acarlomagno** [KosalaHerath/macos-installer-builder#21]
Hi,
Is it possible to insert commands / calls in the post install to change a default MacOS program?
For example ask to change the e-mail program or the browser?

regards
Antonello

**Comment by KosalaHerath** [comment]
Hope this will help: 
https://github.com/palantir/jamf-pro-scripts/blob/main/scripts/Set%20Default%20Browser%20and%20Email%20Client.sh
