### ISSUE TITLE
Payload path option

### ISSUE THREAD

**Issue by itsnestee** [KosalaHerath/macos-installer-builder#23]
Hello @KosalaHerath, Is there a possibility for me to choose the directory of the file inside the installer? 
For instance, I have a plugin that needs to be placed in -/Library/Audio/Plug-ins/Components.

How can do this in macos-installer-builder? 

Thanks
<img width="1680" alt="Screenshot 2022-11-25 at 10 14 51" src="https://user-images.githubusercontent.com/81882275/203944381-a5aa9343-fe33-4c77-999e-22fa3ef04e9d.png">

**Comment by KosalaHerath** [comment]
Hi, you can do it using the postscript. First, install(copy) all the files into a files installation directory. Then, using the postscript move the files to the specific directory.
