### ISSUE TITLE
can't create .pkg file in the target directory

### ISSUE THREAD

**Issue by bolunfeng** [KosalaHerath/macos-installer-builder#3]
hi:
   I have an c++ executable program and want to make it into a pkg format installation package.
   I copy it to the macOS-x64/application/
   then run : 
  bash ./macOS-x64/build-macos-x64.sh gtz_set 2.1.2

cat: ./utils/ascii_art.txt: No such file or directory

Application Name : gtz_set
Application Version : 2.1.2
[2020-01-15 11:52:46][WARN] Apache Maven was not found. Please install Maven first.
[2020-01-15 11:52:46][WARN] Ballerina was not found. Please install ballerina first.
[2020-01-15 11:52:46][INFO] Installer generating process started.
[2020-01-15 11:52:46][INFO] Cleaning target directory.
cp: darwin: No such file or directory
chmod: target/darwin/scripts: No such file or directory
chmod: target/darwin/Resources: No such file or directory
chmod: target/darwin/Distribution: No such file or directory
sed: target/darwin/scripts/postinstall: No such file or directory
sed: target/darwin/scripts/postinstall: No such file or directory
chmod: target/darwin/scripts/postinstall: No such file or directory
sed: target/darwin/Distribution: No such file or directory
sed: target/darwin/Distribution: No such file or directory
chmod: target/darwin/Distribution: No such file or directory
sed: target/darwin/Resources/*.html: No such file or directory
sed: target/darwin/Resources/*.html: No such file or directory
chmod: target/darwin/Resources/: No such file or directory
cp: ./application/.: No such file or directory
cp: darwin/Resources/uninstall.sh: No such file or directory
sed: target/darwinpkg/Library/gtz_set/2.1.2/uninstall.sh: No such file or directory
sed: target/darwinpkg/Library/gtz_set/2.1.2/uninstall.sh: No such file or directory
[2020-01-15 11:52:46][INFO] Application installer generation process started.(3 Steps)
[2020-01-15 11:52:46][INFO] Apllication installer package building started.(1/3)
[2020-01-15 11:52:46][INFO] Application installer product building started.(2/3)
Do you wish to sign the installer (You should have Apple Developer Certificate) [y/N]?N
[2020-01-15 11:52:46][INFO] Skiped signing process.
[2020-01-15 11:52:46][INFO] Application installer generation steps finished.
[2020-01-15 11:52:46][INFO] Installer generating process finished 

at last ,I can't find the pkg file in the  macos-installer-builder/target....

I need your help....thanks!

**Comment by ducatimo** [comment]
@bolunfeng  
looks like you need to start the script from "macOS-x64" as current directory
(just had same problem)

bash ./build-macos-x64.sh gtz_set 2.1.2

**Comment by KosalaHerath** [comment]
> @bolunfeng
> looks like you need to start the script from "macOS-x64" as current directory
> (just had same problem)
> 
> bash ./build-macos-x64.sh gtz_set 2.1.2

Yes correct. The command should run as following:

`bash <PRODUCT_HOME>/macOS-x64/build-macos-x64.sh [APPLICATION_NAME] [APPLICATION_VERSION]`

For more details please refer the explained details in the blog: https://medium.com/swlh/the-easiest-way-to-build-macos-installer-for-your-application-34a11dd08744

**Comment by KosalaHerath** [comment]
Since the matter has been answered closing the issue.
