### ISSUE TITLE
Member-only story !?

### ISSUE THREAD

**Issue by indexofrefraction** [KosalaHerath/macos-installer-builder#32]
https://medium.com/swlh/the-easiest-way-to-build-macos-installer-for-your-application-34a11dd08744

No documentation, and the linked info is a "Member-only story" ? 
This is really a seller for this project ...

**Comment by KosalaHerath** [comment]
Update the README with essential instructions (https://github.com/KosalaHerath/macos-installer-builder/commit/89fa0ec9fcd5c502439089cb4c6e9e6af38be27d)
