### ISSUE TITLE
why is it installing in library folder and not in application

### ISSUE THREAD

**Issue by ff6f8d68** [KosalaHerath/macos-installer-builder#36]

**Comment by KosalaHerath** [comment]
The WSO2 products primarily operate as background services via the terminal. Therefore, the example does not require the files to be located in the Application folder.

If you want to install in Application folder, please refer to these responses: 

https://github.com/KosalaHerath/macos-installer-builder/issues/11#issuecomment-787552008

https://github.com/KosalaHerath/macos-installer-builder/issues/33#issue-1813262333

I hope this will help with your issue 😇
