### ISSUE TITLE
Terms of Service step

### ISSUE THREAD

**Issue by mikeumus** [KosalaHerath/macos-installer-builder#8]
How might you add a Terms of Service page to the installer? 

Thank you.

**Comment by KosalaHerath** [comment]
Hi Micheal,

You can add a License or Terms of Service to your product installer, prepare a license file in one of the supported formats (including RTF, HTML, and plain text) and add it to 

`<PRODUCT_HOME>/macOS-x64/darwin/Resources/`

directory. Then add its reference to the distribution file using a <license/> element to the distribution file root element <installer-gui-script/>:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<installer-script minSpecVersion="1.000000">
    <title>__PRODUCT__</title>
    <background mime-type="image/png" file="banner.png" scaling="proportional"/>
     ...
    <license file="LICENSE.html"/>
     ...
</installer-gui-script>
```

Then you can find it in the installation windows before and the user needs it to accept before proceeding as following:

<img width="620" alt="Screen Shot 2020-09-22 at 5 36 15 pm" src="https://user-images.githubusercontent.com/33099111/93855114-5073a080-fcfa-11ea-9cf4-9787767e3325.png">

Hope this will help you. 😇

**Comment by KosalaHerath** [comment]
Since improvement is added https://github.com/KosalaHerath/macos-installer-builder/commit/3eed0d20ef99fbc0b9767449e1d9694a9f15ea7f closing the issue.

**Comment by KosalaHerath** [comment]
Since improvement is added https://github.com/KosalaHerath/macos-installer-builder/commit/3eed0d20ef99fbc0b9767449e1d9694a9f15ea7f closing the issue.

**Comment by mikeumus** [comment]
Yes, this helps.
Thank you @KosalaHerath
